### ISSUE TITLE
Suddenly started getting this error

### ISSUE THREAD

**Issue by Solacezz** [ESX-Org/esx_joblisting#14]
suddenly started getting this error

Error running call reference function for resource esx_joblisting: citizen:/scripting/lua/scheduler.lua:351: server/main.lua:30: attempt to index a nil value (upvalue ‘xPlayer’)
stack traceback:
server/main.lua:30: in upvalue ‘ref’
citizen:/scripting/lua/scheduler.lua:337: in function citizen:/scripting/lua/scheduler.lua:336
[C]: in function ‘xpcall’
citizen:/scripting/lua/scheduler.lua:336: in function citizen:/scripting/lua/scheduler.lua:335
stack traceback:
[C]: in function ‘error’
citizen:/scripting/lua/scheduler.lua:351: in function citizen:/scripting/lua/scheduler.lua:322
Error: Unhandled error Error: BUFFER_SHORTAGE
at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
at h (citizen:/scripting/v8/msgpack.js:29:15761)
at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
at unpack (citizen:/scripting/v8/main.js:20:33)
at citizen:/scripting/v8/main.js:48:11
at setImmediate (mysql-async.js:5039:9)
at Object.callback (citizen:/scripting/v8/timer.js:56:6)

**Comment by RolexxGaming** [comment]
Same here. The exact error I am getting is below.

Error running call reference for resource esx_joblisting: citizen:/scripting/lua/scheduler.lua:30: attempt to index a nil value (upvalue 'xPlayer')
stack traceback:
server/main.lua:30: in upvalue 'ref'
citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
[C]: in function 'xpcall'
citizen:/scripting/lua/scheduler.lua:388; in function <citizen:/scripting/lua/scheduler.lua:372>

Error: Unhandled error in timer: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
at n.e [as reserver] (citizen:/scripting/v8/msgpack.js:29:12766)
at h (citizen:/scripting/v8/msgpack.js:29:15761)
at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
at unpack (citizen:/scripting/v8/main.js:20:33)
at citizen:/scripting/v8/main.js:51:11
at setImmediate (mysql-async .js:4962:9)
at Object.callback (citizen:/scripting/v8/timer.js:96:21)
